name: Environment Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an Environment to run the action"
        required: true
        type: choice
        options:
          - QA
          - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Selected Environment
        run: echo "Environment ${{ inputs.environment }}"

  devStage:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.environment == 'dev' }}
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: devStage
        run: pwd
      - name: Sleep
        run: sleep 5

  QAstage:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.environment == 'QA' }}
    environment: QA
    steps:
      - uses: actions/checkout@v4
      - name: QAstage
        run: echo "QAstage"
      - name: Sleep
        run: sleep 5
