name: Environment Test

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      option:
        description: "Choose an Environment to run the action"
        required: true
        type: choice
        options:
          - QA
          - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Environment specific
      run: |
        run: echo "Environment : ${{ github.event.inputs.option }}"
        
  devStage:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - name: devStage
      run: |
        pwd
    - name: Sleep
      run: |
        sleep 5
        
  QAstage:
    runs-on: ubuntu-latest
    needs: build
    environment: QA
    steps:
    - uses: actions/checkout@v4
    - name: QAstage
      run: |
        echo "QAstage"
    - name: Sleep
      run: |
        sleep 5     
