name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        pwd
    - name: Run Tests
      run: |
        ls
  secondstage:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        pwd
    - name: Run Tests
      run: |
        ls
